......F...
======================================================================
FAIL: test_contains_negative_with_negative_zero (__main__.TestContainsNegative.test_contains_negative_with_negative_zero)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rpommes/1Zentrum/Uni/24SoSe/Bachelorarbeit/1Project/Software/created_scripts/test-script-fixed.py", line 25, in test_contains_negative_with_negative_zero
    self.assertTrue(contains_negative([-0.0]))  # Change it from [-0] to [-0.0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true

----------------------------------------------------------------------
Ran 10 tests in 0.000s

FAILED (failures=1)
